/* eslint-disable jsx-a11y/alt-text */
import Head from "next/head";
import NextImage from "next/image";
import { Inter } from "next/font/google";
import styles from "@/styles/Home.module.css";
import { useState } from "react";

const inter = Inter({ subsets: ["latin"] });

type ImageProps = { id: number };
const Image = ({ id }: ImageProps) => (
  <div className={styles.wrapper}>
    <NextImage
      src={`https://picsum.photos/id/${id}/2000/200`}
      alt="Test"
      fill
      style={{ objectFit: "cover" }}
    />
  </div>
);

export default function Home() {
  const [view, setView] = useState("1");

  const View1 = () => {
    const array = [...Array(1).keys()];
    return (
      <>
        <button onClick={() => setView("2")}>Change view</button>
        <>
          {array.map((x) => (
            <Image key={x} id={x}></Image>
          ))}
        </>
      </>
    );
  };
  const View2 = () => {
    const array = [...Array(100).keys()];
    return (
      <>
        <button onClick={() => setView("1")}>Change view</button>
        {array.map((x) => (
          <Image key={x} id={x}></Image>
        ))}
      </>
    );
  };

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={`${styles.main} ${inter.className}`}>
        {view === "1" && <View1></View1>}
        {view === "2" && <View2></View2>}
      </main>
    </>
  );
}
